version: "3.8"

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/var/www/html
        depends_on:
            - mysql

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3030:3030"
        volumes:
            - ./frontend:/app
        command: npm run dev

    pgsql:
        image: mysql:8
        environment:
            POSTGRESSQL_ROOT_PASSWORD: root
            POSTGRESSQL_DATABASE: myapp
            POSTGRESSQL_USER: user
            POSTGRESSQL_PASSWORD: password
        ports:
            - "3306:3306"
